"""
Convert PDF to LaTeX
Extracts text from PDF and formats as LaTeX document
"""

import fitz  # PyMuPDF
import re

def extract_text_from_pdf(pdf_path):
    """Extract all text from PDF"""
    doc = fitz.open(pdf_path)
    text = ""
    
    for page_num, page in enumerate(doc):
        text += f"\n%% Page {page_num + 1}\n"
        text += page.get_text()
    
    doc.close()
    return text

def convert_to_latex(text):
    """Convert plain text to basic LaTeX formatting"""
    latex = text
    
    # Convert chapter/section headings
    latex = re.sub(r'^CHAPTER\s*(\d+)', r'\\chapter{\1}', latex, flags=re.MULTILINE)
    latex = re.sub(r'^Section\s*(\d+\.?\d*)', r'\\section{\1}', latex)
    latex = re.sub(r'^(\d+\.?\d*)\s', r'\\subsection{\1} ', latex)
    
    # Convert equations (basic patterns)
    latex = re.sub(r'(\d+\.?\d*)\s*=\s*([\d\.\+\-\*/\s]+)', r'$\1 = \2$', latex)
    
    # Convert bullet points
    latex = re.sub(r'^[\•\*]\s+', r'\\item ', latex, flags=re.MULTILINE)
    
    # Convert numbered lists
    latex = re.sub(r'^(\d+)\.\s+', r'\\item[\1] ', latex, flags=re.MULTILINE)
    
    # Clean up multiple spaces
    latex = re.sub(r'  +', ' ', latex)
    
    return latex

def create_latex_document(content, output_path):
    """Create complete LaTeX document"""
    
    latex_doc = r"""\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{graphicx}
\usepackage{geometry}
\geometry{margin=1in}

\title{Document Converted from PDF}
\author{Generated by Clawdbot}
\date{\today}

\begin{document}

\maketitle
\tableofcontents
\newpage

"""
    
    latex_doc += content
    
    latex_doc += r"""
\end{document}
"""
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(latex_doc)
    
    return latex_doc

# Main execution
pdf_path = r"C:\Users\bainz\Downloads\testrun.pdf"
output_path = r"C:\Users\bainz\clawd\testrun_converted.tex"

print("=" * 60)
print("PDF TO LATEX CONVERTER")
print("=" * 60)
print()
print(f"Input:  {pdf_path}")
print(f"Output: {output_path}")
print()

# Extract text
print("Extracting text from PDF...")
raw_text = extract_text_from_pdf(pdf_path)

if raw_text.strip():
    print(f"[OK] Extracted {len(raw_text)} characters")
    
    # Convert to LaTeX
    print("Converting to LaTeX format...")
    latex_content = convert_to_latex(raw_text)
    
    # Create complete document
    print("Creating LaTeX document...")
    full_latex = create_latex_document(latex_content, output_path)
    
    print()
    print("=" * 60)
    print("CONVERSION COMPLETE!")
    print("=" * 60)
    print()
    print(f"LaTeX file created: {output_path}")
    print()
    print("To compile to PDF, run:")
    print("  pdflatex testrun_converted.tex")
    print()
    print("Preview of extracted text:")
    print("-" * 60)
    print(raw_text[:1000])
    print("-" * 60)
    print()
    print("NOTE: Basic formatting applied. Manual review recommended!")
    print("=" * 60)
else:
    print("[ERROR] No text found in PDF (may be scanned image)")
    print("For scanned PDFs, use OCR tools like Mathpix or Tesseract")
